const { after } = require("./bugOrNot");

module.exports = {
    beforeEach: browser => browser.url('https://alpha.yoodlize.com'),
    after: browser => browser.end(),

    'See All Test': browser => {
        browser
        browser.maximizeWindow()
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[1]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Recreational Vehicles")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[2]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Outdoor Gear")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[3]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Electronics")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[4]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Party & Wedding Equipment")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[5]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Tools")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[6]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Clothing")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[7]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Home and Kitchen")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[8]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Toys and Games")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[9]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Lawn and Garden")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[10]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Sporting Equipment")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[11]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "DVDs")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[12]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Venues")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[13]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Music")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[14]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Business Equipment")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[15]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Misc")
    }

    'Category Test': browser => {
        browser
        browser.maximizeWindow()
        .useXpath()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[1]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Tools")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[2]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Outdoor Gear")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[3]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Electronics")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[4]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Party & Wedding Equipment")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[5]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Recreational Vehicles")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[6]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Clothing")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[7]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Home and Kitchen")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[8]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Toys and Games")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[9]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Lawn and Garden")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[10]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Sporting Equipment")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[11]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "DVDs")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[12]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Venues")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[13]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Music")
        browser.url('https://alpha.yoodlize.com')
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[14]')
        .assert.containsText(('//div[@class="sc-jKVCRD jSqgxr"]'), "Misc")
    }
}